### ISSUE TITLE
Some questions about prepare_synthetic.py

### ISSUE THREAD

**Issue by KID-22** [georgehc/mnar_mc#1]
In function estimate_propensities_naive_bayes_MAR, I wonder why need x_total = x_train + x_mar.
In paper Recommendations as treatments: Debiasing learning and evaluation, the  P(Y = r) is calculate only from a small sample of MCAR data rather than x_train + x_mar. I think here should be x_mar.
Besides, could you please tell me that is there any tricks about why min_prob is set at 0.05?
Hope to your reply.
Thank you!

**Comment by georgehc** [comment]
Hello! This was a bug in the old code and has been fixed (note that that specific calculation has been moved to models.py and the function is called estimate_propensities_naive_bayes) in a recent code update (some ~15 days back). The minimum probability is an arbitrary threshold that we're using in different parts of our code to prevent entries with extremely low estimated propensity scores from dominating the debiased loss in matrix completion (specifically we debias matrix completion losses by dividing an entry by its estimated probability of being revealed; if this probability is too small then matrix completion will focus on getting these extremely rarely occurring entries right). In practice you may want to tune this min_prob threshold as a hyperparameter.

**Comment by KID-22** [comment]
Thanks for your reply!
